version: '3'
services:
  database:
    build: .
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
     - ./oradata:/u01/app/oracle/oradata
    environment: 
      - ORACLE_PWD=<your password>
      - INIT_SGA_SIZE=1024
      - INIT_PGA_SIZE=1024
